version: "3"

services:
  ## Data Base
  db:
    image: postgres:15.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: postgres
    mem_reservation: 512M
    mem_limit: 1G
    networks:
      brige:
        aliases:
          - db

  ## listener monit transcion
  listener:
    build: ./listener/
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
      PROVIDER: https://rpc-evm-sidechain.xrpl.org
      PHRASE_HD_WALLET: "remove scheme silver sugar text circle salt manage long little sword amount"
      MASTER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
    networks:
      brige:
        aliases:
          - listener
    depends_on:
      - db

  back-end:
    build: ./back-end/
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      JWT_SECRET: 14589632
      JWT_EXPIRES_IN: 1d
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
      PROVIDER: 'https://rpc-evm-sidechain.xrpl.org'
      PRIVATE_KEY: 'ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
    networks:
      brige:
        aliases:
          - back-end
    depends_on:
      - listener
      - db

      
  ## client web
  app:
    build: ./app/
    ports:
      - "80:80"
    environment:
      VITE_BASE_URL: http://back-end:8000
    networks:
      brige:
        aliases:
          - app
    depends_on:
      - db
      - back-end
    
networks:
  brige:
